name: Docker Image CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * 0'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag aha:$(date +%s)
    - name: Publish Docker image
      uses: elgohr/Publish-Docker-Github-Action@v2.11
      with:
        name: stanfordaha/garnet
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest"
        cache: ${{ github.event_name != 'schedule' }}
