name: Integration Tests

on:
  push:
    branches-ignore: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build Docker Image
      run: docker build .
